
services:
  db:
    image: postgres:14.3
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    container_name: postgres_db
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: